version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge